# Generated by Django 3.0.7 on 2020-07-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
    ]
