# Generated by Django 3.0.7 on 2020-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_customer_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/comingsoon.jpg', null=True, upload_to=''),
        ),
    ]
